name:                fakedata
version:             1.0.4
github:              "psibi/fakedata"
license:             BSD3
author:              "Sibi Prabakaran"
maintainer:          "sibi@psibi.in"
copyright:           "Sibi Prabakaran"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- faker/lib/locales/*yml
- faker/lib/locales/en/*yml
- faker/lib/locales/ja/*yml
- faker/lib/locales/fr/*yml
- customFakeSource/en/*yml

# Metadata used when publishing your package
synopsis:            Library for producing fake data
category:            Random, Fake, FakeData

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psibi/fakedata#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- random
- text
- exceptions
- vector
- yaml
- directory
- filepath
- unordered-containers
- hashable
- containers
- template-haskell
- bytestring
- time
- string-random
- fakedata-parser
- attoparsec
- transformers

library:
  source-dirs: src
  other-modules:
  - Paths_fakedata
  - Config
  - Faker.TH
  - Faker.Provider.Address
  - Faker.Provider.Adjective
  - Faker.Provider.Ancient
  - Faker.Provider.Animal
  - Faker.Provider.App
  - Faker.Provider.Appliance
  - Faker.Provider.AquaTeenHungerForce
  - Faker.Provider.Artist
  - Faker.Provider.BackToTheFuture
  - Faker.Provider.Bank
  - Faker.Provider.Barcode
  - Faker.Provider.Basketball
  - Faker.Provider.Beer
  - Faker.Provider.BigBangTheory
  - Faker.Provider.Bird
  - Faker.Provider.Blood
  - Faker.Provider.BoJackHorseman
  - Faker.Provider.Book
  - Faker.Provider.BossaNova
  - Faker.Provider.BreakingBad
  - Faker.Provider.Buffy
  - Faker.Provider.Business
  - Faker.Provider.Camera
  - Faker.Provider.Cannabis
  - Faker.Provider.Cat
  - Faker.Provider.Chiquito
  - Faker.Provider.ChuckNorris
  - Faker.Provider.ClashOfClans
  - Faker.Provider.Code
  - Faker.Provider.Coffee
  - Faker.Provider.Coin
  - Faker.Provider.Color
  - Faker.Provider.Commerce
  - Faker.Provider.Community
  - Faker.Provider.Company
  - Faker.Provider.Compass
  - Faker.Provider.Computer
  - Faker.Provider.Conan
  - Faker.Provider.Construction
  - Faker.Provider.Control
  - Faker.Provider.Cosmere
  - Faker.Provider.CryptoCoin
  - Faker.Provider.CultureSeries
  - Faker.Provider.Currency
  - Faker.Provider.DcComics
  - Faker.Provider.Demographic
  - Faker.Provider.Departed
  - Faker.Provider.Dessert
  - Faker.Provider.Device
  - Faker.Provider.Dnd
  - Faker.Provider.Dog
  - Faker.Provider.Doraemon
  - Faker.Provider.Dota
  - Faker.Provider.DragonBall
  - Faker.Provider.DrivingLicense
  - Faker.Provider.Drone
  - Faker.Provider.DrWho
  - Faker.Provider.DumbAndDumber
  - Faker.Provider.Dune
  - Faker.Provider.Educator
  - Faker.Provider.ElderScrolls
  - Faker.Provider.ElectricalComponents
  - Faker.Provider.Esport
  - Faker.Provider.Fallout
  - Faker.Provider.FamilyGuy
  - Faker.Provider.File
  - Faker.Provider.FinalSpace
  - Faker.Provider.Finance
  - Faker.Provider.Food
  - Faker.Provider.Football
  - Faker.Provider.FreshPrinceOfBelAir
  - Faker.Provider.Friends
  - Faker.Provider.FunnyName
  - Faker.Provider.Futurama
  - Faker.Provider.GameOfThrones
  - Faker.Provider.Gender
  - Faker.Provider.Ghostbusters
  - Faker.Provider.GratefulDead
  - Faker.Provider.GreekPhilosophers
  - Faker.Provider.Hacker
  - Faker.Provider.HalfLife
  - Faker.Provider.HarryPotter
  - Faker.Provider.Heroes
  - Faker.Provider.HeroesOfTheStorm
  - Faker.Provider.HeyArnold
  - Faker.Provider.Hipster
  - Faker.Provider.HitchhikersGuideToTheGalaxy
  - Faker.Provider.Horse
  - Faker.Provider.House
  - Faker.Provider.HowIMetYourMother
  - Faker.Provider.HowToTrainYourDragon
  - Faker.Provider.IndustrySegments
  - Faker.Provider.Internet
  - Faker.Provider.JackHandey
  - Faker.Provider.Job
  - Faker.Provider.Kpop
  - Faker.Provider.LeagueOfLegends
  - Faker.Provider.Lebowski
  - Faker.Provider.Lorem
  - Faker.Provider.Lovecraft
  - Faker.Provider.Markdown
  - Faker.Provider.Marketing
  - Faker.Provider.Measurement
  - Faker.Provider.MichaelScott
  - Faker.Provider.Military
  - Faker.Provider.Minecraft
  - Faker.Provider.Mountain
  - Faker.Provider.Movie
  - Faker.Provider.Music
  - Faker.Provider.Myst
  - Faker.Provider.Name
  - Faker.Provider.Naruto
  - Faker.Provider.Nation
  - Faker.Provider.NatoPhoneticAlphabet
  - Faker.Provider.NewGirl
  - Faker.Provider.OnePiece
  - Faker.Provider.Opera
  - Faker.Provider.Overwatch
  - Faker.Provider.ParksAndRec
  - Faker.Provider.PearlJam
  - Faker.Provider.Phish
  - Faker.Provider.PhoneNumber
  - Faker.Provider.Pokemon
  - Faker.Provider.Prince
  - Faker.Provider.PrincessBride
  - Faker.Provider.ProgrammingLanguage
  - Faker.Provider.Quote
  - Faker.Provider.Rajnikanth
  - Faker.Provider.Relationship
  - Faker.Provider.Restaurant
  - Faker.Provider.RickAndMorty
  - Faker.Provider.RockBand
  - Faker.Provider.Room
  - Faker.Provider.Rupaul
  - Faker.Provider.Rush
  - Faker.Provider.Science
  - Faker.Provider.Seinfeld
  - Faker.Provider.Shakespeare
  - Faker.Provider.Show
  - Faker.Provider.SiliconValley
  - Faker.Provider.Simpsons
  - Faker.Provider.SlackEmoji
  - Faker.Provider.SonicTheHedgehog
  - Faker.Provider.Source
  - Faker.Provider.SouthPark
  - Faker.Provider.Space
  - Faker.Provider.Stargate
  - Faker.Provider.StarTrek
  - Faker.Provider.StarWars
  - Faker.Provider.StrangerThings
  - Faker.Provider.StreetFighter
  - Faker.Provider.StudioGhibli
  - Faker.Provider.Subscription
  - Faker.Provider.Suits
  - Faker.Provider.Superhero
  - Faker.Provider.SuperMario
  - Faker.Provider.SuperSmashBros
  - Faker.Provider.SwordArtOnline
  - Faker.Provider.Tea
  - Faker.Provider.Team
  - Faker.Provider.TH
  - Faker.Provider.TheExpanse
  - Faker.Provider.TheItCrowd
  - Faker.Provider.TheThickOfIt
  - Faker.Provider.Tolkien
  - Faker.Provider.Touhou
  - Faker.Provider.TwinPeaks
  - Faker.Provider.UmphreysMcgee
  - Faker.Provider.University
  - Faker.Provider.Vehicle
  - Faker.Provider.VentureBros
  - Faker.Provider.Verbs
  - Faker.Provider.VForVendetta
  - Faker.Provider.Volleyball
  - Faker.Provider.WarhammerFantasy
  - Faker.Provider.Witcher
  - Faker.Provider.WorldCup
  - Faker.Provider.WorldOfWarcraft
  - Faker.Provider.Yoda
  - Faker.Provider.Zelda

tests:
  fakedata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover:hspec-discover
    dependencies:
    - fakedata
    - hspec
    - vector
    - time
    - QuickCheck
    - regex-tdfa

benchmarks:
  fakebench:
    main: main.hs
    source-dirs: bench
    dependencies:
    - fakedata
    - gauge
    - deepseq
    ghc-options:
    - -O2
