jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 180
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      GHC 8.4:
        ARGS: "--resolver lts-12"
      GHC 8.6:
        ARGS: "--resolver lts-14"
      GHC 8.8:
        ARGS: "--resolver lts-15"
      nightly:
        ARGS: "--resolver nightly"
  variables:
    CACHE_STACK_ROOT: "$(Build.SourcesDirectory)/.stack-root"
    CACHE_STACK_WORK: "$(Build.SourcesDirectory)/.stack-work"
  steps:
  - checkout: self
    submodules: true
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Stack Installation'
  - script: |
      export PATH=$HOME/.local/bin:$PATH
      export CACHE_PGM_DIR=/home/vsts/work/1/s/.stack-root/programs/x86_64-linux
      echo "##vso[task.setvariable variable=CACHE_ROOT]$CACHE_STACK_ROOT"
      echo "##vso[task.setvariable variable=CACHE_WORK]$CACHE_STACK_WORK"
      echo "##vso[task.setvariable variable=CACHE_PROGRAMS]$CACHE_PGM_DIR"
    displayName: 'Set Cache Variables'
  - task: Cache@2
    inputs:
      key: "stack-root $(Agent.OS) | $(ARGS) | stack.yaml | package.yaml"
      restoreKeys: |
        "stack-root $(Agent.OS) | $(ARGS)"
        "stack-root $(Agent.OS)"
      path: $(CACHE_ROOT)
    displayName: Cache Stack root
  - task: Cache@2
    inputs:
      key: "stack-work $(Agent.OS) | $(ARGS) | stack.yaml | package.yaml"
      restoreKeys: |
        "stack-work $(Agent.OS) | $(ARGS)"
        "stack-work $(Agent.OS)"
      path: $(CACHE_WORK)
    displayName: Cache Stack work
  - task: Cache@2
    inputs:
      key: "stack-programs $(Agent.OS) | $(ARGS) | stack.yaml | package.yaml"
      restoreKeys: |
        "stack-programs $(Agent.OS) | $(ARGS)"
        "stack-programs $(Agent.OS)"
      path: $(CACHE_PROGRAMS)
    displayName: Cache Stack programs
  - script: |
      export PATH=$HOME/.local/bin:$PATH
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export STACK_WORK=".stack-work";
      export PGM=$(stack $ARGS path --programs 2> /dev/null);
      echo $CACHE_PROGRAMS
      echo $PGM
      test $CACHE_PROGRAMS = $PGM
    displayName: 'Test cache paths'
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and Test'
